### ISSUE TITLE
Implement gradients

### ISSUE THREAD

**Issue by Kraahkan** [Kraahkan/DELVE#24]
https://imgur.com/a/Aqc6FH2

**Comment by c1Koriginal** [comment]
Animated gradients
https://www.youtube.com/watch?v=x_DXXGvyfh8

**Comment by c1Koriginal** [comment]
http://angrytools.com/gradient/

**Comment by c1Koriginal** [comment]
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle" >
<gradient
android:type="linear"
android:startColor="#FFcfd9df"
android:endColor="#FFE2EBF0"
android:angle="90"/>
</shape>

-------------------------------------------------
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle" >
<gradient
android:type="radial"
android:centerX="50%"
android:centerY="50%"
android:startColor="#FFcfd9df"
android:endColor="#FFE2EBF0"
android:gradientRadius="100"/>
</shape>



<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle" >
<gradient
android:type="linear"
android:startColor="#FFfdfbfb"
android:endColor="#FFebedee"
android:angle="315"/>
</shape>

-------------------------------------------------
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle" >
<gradient
android:type="radial"
android:centerX="50%"
android:centerY="50%"
android:startColor="#FFfdfbfb"
android:endColor="#FFebedee"
android:gradientRadius="100"/>
</shape>

**Comment by c1Koriginal** [comment]
https://colorpalettes.net/color-palette-2492/
https://colorpalettes.net/color-palette-2488/
https://colorpalettes.net/color-palette-2208/
https://colorpalettes.net/color-palette-2599/
https://colorpalettes.net/color-palette-2577/
https://colorpalettes.net/color-palette-2566/
https://colorpalettes.net/color-palette-2565/
